name: Publish Package to npmjs
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          registry-url: 'https://registry.npmjs.org' 
      # Install PNPM
      - name: Install PNPM
        run: npm install -g pnpm
      # Install dependencies with PNPM
      - name: Install Dependencies
        run: pnpm install
      # Build the package with PNPM
      - name: Build
        run: pnpm run build
      # Publish the package to npm with PNPM
      - name: Publish
        run: pnpm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
